# -*- coding: utf-8 -*-
"""Exp11_23UAI304

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/136Qgf1PsOtE_FJxX_lkxN0Tmy1tTGH31
"""

!pip install transformers
!pip install torch

from transformers import pipeline

# Initialize the summarization pipeline using a pre-trained model (e.g., BART or T5)
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def summarize_text(text):
    # Summarize the given text
    summary = summarizer(text, max_length=150, min_length=50, do_sample=False)
    return summary[0]['summary_text']

# Take user input for text to summarize
user_input = input("Please enter a paragraph to summarize: ")

# Call the summarize function
summary = summarize_text(user_input)

# Display the result
print("\nOriginal Text:\n", user_input)
print("\nSummarized Text:\n", summary)